"""基础设施层

提供技术能力实现：数据库、网络、文件系统、配置管理等。
"""

from .api import RSSHubRadarAPI
from .config import (
    BasicConfig,
    FFmpegConfig,
    GlobalConfig,
    RsshubPluginConfig,
    SenderStrategiesConfig,
    TranslationConfig,
)
from .fetcher import (
    Enclosure,
    EntryParsed,
    FeedDiscoverer,
    FeedDiscoveryResult,
    HttpFetcher,
    RSSFeedFetcher,
    RSSParser,
    WebFeed,
)
from .media import MediaDownloader
from .messaging import (
    BaseEvent,
    BaseMessageSender,
    ChannelInfo,
    DefaultMessageSender,
    EventBus,
    Extension,
    InfrastructureMessageSenderAdapter,
    InfrastructureMessageSenderProvider,
    MessageContext,
    NotificationServiceImpl,
    OneBotMessageSender,
    PluginManager,
    PreparedMedia,
    QQOfficialMessageSender,
    SendResult,
    TelegramMessageSender,
    get_bot_self_id,
    get_event_bus,
    get_notification_service,
    get_plugin_manager,
    get_sender_for_platform,
    on_event,
    register_sender,
    set_bot_self_id_provider,
)
from .persistence import (
    DatabaseManager,
    FeedORM,
    FeedRepositoryImpl,
    PushHistoryORM,
    PushHistoryRepositoryImpl,
    RSSHubBaseModel,
    SubORM,
    SubscriptionRepositoryImpl,
    TranslationCacheORM,
    UserORM,
    UserRepositoryImpl,
    get_database,
    get_feed_repository,
    get_push_history_repository,
    get_subscription_repository,
    get_user_repository,
)
from .schedule import RSSScheduler, SchedulerStats
from .utils import (
    AsyncTool,
    BaseCache,
    CompiledExpression,
    ExpressionEvaluator,
    ExpressionParser,
    FFmpegTool,
    LockManager,
    cacheevict,
    cacheput,
    caching,
    get_logger,
    get_memory_cache,
    locked,
    set_cache_backend,
)

__all__ = [
    # Fetcher
    "HttpFetcher",
    "WebFeed",
    "RSSFeedFetcher",
    "RSSParser",
    "EntryParsed",
    "Enclosure",
    "FeedDiscoverer",
    "FeedDiscoveryResult",
    # Schedule
    "RSSScheduler",
    "SchedulerStats",
    # Messaging - Senders
    "SendResult",
    "PreparedMedia",
    "ChannelInfo",
    "MessageContext",
    "BaseMessageSender",
    "DefaultMessageSender",
    "TelegramMessageSender",
    "OneBotMessageSender",
    "QQOfficialMessageSender",
    "InfrastructureMessageSenderAdapter",
    "InfrastructureMessageSenderProvider",
    "get_sender_for_platform",
    "register_sender",
    "get_bot_self_id",
    "set_bot_self_id_provider",
    # Messaging - Events
    "BaseEvent",
    "EventBus",
    "get_event_bus",
    # Messaging - Extensions
    "Extension",
    "PluginManager",
    "get_plugin_manager",
    "on_event",
    # Messaging - Notification
    "NotificationServiceImpl",
    "get_notification_service",
    # Config
    "BasicConfig",
    "GlobalConfig",
    "FFmpegConfig",
    "TranslationConfig",
    "SenderStrategiesConfig",
    "RsshubPluginConfig",
    # Persistence
    "DatabaseManager",
    "RSSHubBaseModel",
    "get_database",
    "FeedORM",
    "UserORM",
    "SubORM",
    "PushHistoryORM",
    "TranslationCacheORM",
    "FeedRepositoryImpl",
    "get_feed_repository",
    "UserRepositoryImpl",
    "get_user_repository",
    "SubscriptionRepositoryImpl",
    "get_subscription_repository",
    "PushHistoryRepositoryImpl",
    "get_push_history_repository",
    # Utils
    "get_logger",
    "AsyncTool",
    "LockManager",
    "locked",
    "ExpressionParser",
    "ExpressionEvaluator",
    "CompiledExpression",
    "BaseCache",
    "get_memory_cache",
    "set_cache_backend",
    "caching",
    "cacheput",
    "cacheevict",
    "MediaDownloader",
    "FFmpegTool",
    # API
    "RSSHubRadarAPI",
]
